### ISSUE TITLE
Utilize ES6 features

### ISSUE THREAD

**Issue by queengooborg** [mdn/bob#1118]
We should switch to using ES6 syntax for our internal code, as all modern browsers support ES6 features (and Webpack can use Babel to transpile anything that's not supported yet).

**Comment by NiedziolkaMichal** [comment]
Could you provide more details about what should be changed? The editor already uses async/await, ESM, arrow function, const/let.

**Comment by caugner** [comment]
@queengooborg It looks like this is resolved as a side-effect of migrating to TypeScript!?

**Comment by queengooborg** [comment]
I think that this has mostly been resolved, so let's close this.  👍
