### ISSUE TITLE
Consider extending feature detections for CSS functions

### ISSUE THREAD

**Issue by yarusome** [mdn/bob#1269]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

This section shows the use of `hwb()` through a CSS property, but this functional notation is not supported on my (pretty old) Firefox and it shows like this:

![current](https://user-images.githubusercontent.com/97945148/234778159-acf499d2-7b75-48ff-8c55-ecb0aee41ac7.png)

### What did you expect to see?

![expected](https://user-images.githubusercontent.com/97945148/234778270-f2f9656f-0401-44e4-8357-1317ef15f58a.png)

### Do you have anything more you want to share?

See my comment below for details on adding this feature.

**Comment by yarusome** [comment]
I found the feature detection codes in [mdn/bob](https://github.com/mdn/bob/blob/main/editor/js/editor-libs/mce-utils.js#L25-L46):

```js
export function isPropertySupported(dataset) {
  /* If there are no 'property' attributes,
           there is nothing to test, so return true. */
  if (dataset["property"] === undefined) {
    return true;
  }

  // `property` may be a space-separated list of properties.
  const properties = dataset["property"].split(" ");
  /* Iterate through properties: if any of them apply,
        the browser supports this example. */
  const tmpElem = document.createElement("div");
  let supported = false;

  for (let i = 0, l = properties.length; i < l; i++) {
    if (tmpElem.style[properties[i]] !== undefined) {
      supported = true;
    }
  }

  return supported;
}
```

So it seems enough to make the following change (*caveat below*):

```diff
-    if (tmpElem.style[properties[i]] !== undefined) {
+    if (tmpElem.style[properties[i]] !== undefined && tmpElem.style[properties[i]] !== "") {
        supported = true;
+       break;
     }
```

The rationale is that any example declaration would have a value.

The potential problem here is that example declarations might contain multiple properties as noted in the code comment above. However:

  1. Personally I haven't seen such a live interactive example so far.
  2. It's rather rational to expect or even require (as specifying in the [Interactive examples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#interactive_examples) section) that live interactive examples for CSS functions use only one property in the choice list, since the list width is quite limited.

---

Therefore to move forward, the following suffice:

  1. a PR making the code change above *with testing* (I myself don't have a proper dev environment for this, sorry :pray:), and
  2. possibly a follow-up issue at [mdn/content](https://github.com/mdn/content/issues) proposing the requirement above for live interactive examples.

I could also do Step 2 in case anyone only wants to do Step 1.

**Comment by yarusome** [comment]
@wbamberg Sorry to bother you over here, but could this issue be moved to mdn/bob? I think the key issue lies there.

Thanks in advance :pray:

**Comment by wbamberg** [comment]
No problem, @yarusome !

Thanks for the analysis! @schalkneethling , who is maintaining mdn/bob these days?
