### ISSUE TITLE
Update WASM playground to support the latest features

### ISSUE THREAD

**Issue by pepelsbey** [mdn/bob#1745]
It seems like playground doesn’t support WASM’s `return_call`, which is why [my PR with a demo](https://github.com/mdn/interactive-examples/pull/2693) for Firefox 121 has stalled.

```
> Error: parseWat failed:
3:6: error: opcode not allowed: return_call
    (return_call $fac-aux (local.get $x) (i64.const 1))
     ^^^^^^^^^^^
10:10: error: opcode not allowed: return_call
        (return_call $fac-aux
         ^^^^^^^^^^^
```

WASM docs would benefit from better code demos, but we can’t demo all the features now.

The [wabt.js](https://github.com/AssemblyScript/wabt.js) dependency seems to be the problem. It hasn’t been updated for a while. There might be an alternative solution for running demos, or we could ping the package authors.

**Comment by caugner** [comment]
This was resolved by https://github.com/mdn/bob/pull/1776, and https://github.com/mdn/interactive-examples/pull/2693 is now also merged.
