### ISSUE TITLE
JS example editor output doesn't wrap, makes the whole iframe scroll

### ISSUE THREAD

**Issue by wbamberg** [mdn/bob#272]
This came up in https://github.com/mdn/interactive-examples/pull/1377.

If the output of the example is too long to fit the editor's div#console element, then the entire editor iframe gets a scrollbar.

Perhaps a simple fix would just be to change this: https://github.com/mdn/bob/blob/master/editor/css/editable-js.css#L27 to:

```css
    white-space: pre-wrap;
```
?

**Comment by caugner** [comment]
@wbamberg I looked at the issue you're referencing, but it doesn't mention any URL where the problem appears.

Would you have an example page where this occurs, by any chance?

**Comment by wbamberg** [comment]
The problem is mentioned at https://github.com/mdn/interactive-examples/pull/1377#pullrequestreview-249591777 as an issue for the example added in that PR, but we fixed it in content in that case, so it doesn't appear there.

The original problem was visible any time the console output overflowed the console.

It seems like we still have a version of it. Try https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat - we get 2 horizontal scrollbars, one for the entire editor and one for the console.

We should have 0 horizontal scrollbars, and the console should wrap the output (just like the console in the browser devtools).

**Comment by caugner** [comment]
To remove the _horizontal_ scrollbar, we can indeed change `white-space: pre` to `white-space: pre-wrap` here:

https://github.com/mdn/bob/blob/04c181a396b3c075a6680c20d8497a3fe393bf04/editor/css/editable-js-and-wat.css#L24-L27

(And probably also here:)

https://github.com/mdn/bob/blob/28c31ec392efe83a030115515154c51095bac56f/editor/css/tabbed-editor.css#L115-L119

To remove the _vertical_ scrollbar in this specific example, we could reduce it to 13 repetitions.

## Before

<img width="779" alt="image" src="https://user-images.githubusercontent.com/495429/166510030-38f8fe31-1088-4638-8fc7-e66abc9dd567.png">


## After

<img width="779" alt="image" src="https://user-images.githubusercontent.com/495429/166509866-ed933b26-5aed-41d8-b5b6-354d11616e3b.png">

**Comment by wbamberg** [comment]
> To remove the vertical scrollbar in this specific example, we could reduce it to 13 repetitions.

Ouch, I hadn't seen that vertical scrollbar. But I don't think this is a content problem or should be fixed in content. If the content overflows a particular pane, it's fine for that pane to have a scrollbar, but the editor as a whole should never have scrollbars.

(I mean, there should be a kind of UI fiction that the editor is not in an iframe, but is part of the page.)

But actually, isn't the vertical scrollbar appearing because of the horizontal scrollbar? (because the h. scrollbar adds height, overflowing the iframe)? So if we fix the first, the second is fixed for us?

<img width="674" alt="Screen Shot 2022-05-03 at 11 04 02 AM" src="https://user-images.githubusercontent.com/432915/166514921-ee466b71-4b05-4b18-b240-50af0fe76132.png">

**Comment by caugner** [comment]
> (I mean, there should be a kind of UI fiction that the editor is not in an iframe, but is part of the page.)

@wbamberg I missed this last year, but FWIW the editor will most likely always be in an iframe for security reasons, to limit what scripts inside the editors have access to.

**Comment by wbamberg** [comment]
I understand that - that's why I said *fiction*.

There was an effort to un-iframify them a few years back, but it never went anywhere.
