### ISSUE TITLE
Enable bob to understand standalone JS files for JS examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/bob#367]
At the moment bob expects the source for JS examples to live inside an HTML file like:

```html
<pre>
<code id="static-js">console.log('hello bob!');
</code>
</pre>
```

We'd like to be able to lint the JS source, and this would be easier if the JS source was supplied in standalone JS files, like:

```js
console.log('hello bob!');
```

To enable this, bob needs to understand this way of supplying sources, and to wrap them in the necessary HTML for the editor.

There are some pointers in this comment: https://github.com/mdn/interactive-examples/issues/250#issuecomment-562653910 to the places we'd need to change things.

One additional complexity is that writers can specify that the example is short or long by adding a `data-height="taller"` or `data-height="shorter"` attribute on the `code` block. For example:

* `taller`: [source](https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/proxyhandler/proxyhandler-ownkeys.html#L2), [result](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/ownKeys) 
* `shorter`: [source](https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/date/date-gethours.html#L2), [result](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getHours)

So we might need a way for the author to specify this in meta.json, and bob to understand it. Or perhaps better, bob could automatically set `taller` or `shorter` based on the actual length of the example?

**Comment by schalkneethling** [comment]
@ikarasz I was updating some of our dependencies and realized that we have some examples in this repo one can use to test that Bob still builds everything correctly, by running `npm start` and then accessing the examples via say http://localhost:4444/pages/js/array-concat.html

With that, would you be interested in adding a `.js` example here https://github.com/mdn/bob/tree/master/live-examples/js-examples/array for testing the work we recently merged?

Let me know, thanks!

**Comment by ikarasz** [comment]
@schalkneethling I tested it on localhost with those files and it was working. Do you mean to change a file in the repository and deploy bob with a js soruce as well?

**Comment by schalkneethling** [comment]
> @schalkneethling I tested it on localhost with those files and it was working. Do you mean changing a file in the repository and deploy bob with a js source as well?

Yes. So, the files in there currently all have the `.html` extension. I am thinking if we add at least one that has the `.js` extension then we have a way to be confident that it all works as expected. Hopefully, I did not misunderstand what this does :) Thank you again for your valuable contributions.

**Comment by ikarasz** [comment]
@schalkneethling I've created a pr with some new examples in 3 different heights so we can check the behavior now.

**Comment by wbamberg** [comment]
This is done, thanks to @ikarasz -> https://github.com/mdn/bob/pull/368.
