### ISSUE TITLE
Change npm module name

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#515]
Currently, bob is published as `mdn-bob` on NPM. Change this to publish as follows:
`@mdn/bob`

**Comment by caugner** [comment]
@schalkneethling What are the different steps to accomplish this?

- [ ] Change the package name in `package.json`
- [ ] Update `interactive-examples` to use the new package name

Is that all?

**Comment by schalkneethling** [comment]
I would probably also consider adding a deprecated message to the existing module:
https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions
