### ISSUE TITLE
Enabling Dark Reader kills the example output

### ISSUE THREAD

**Issue by saschanaz** [mdn/bob#538]
**Summary**
Opening a page with example shows broken output when Dark Reader is enabled.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Enable [Dark Reader](https://darkreader.org/) extension
2. Open https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color
3. See the example output exists

**Actual behavior**

![image](https://user-images.githubusercontent.com/3396686/97087212-a785d180-1628-11eb-8ae9-3a626f5e8419.png)

**Expected behavior**
Output should appear

**Additional context**
Tossed from https://github.com/darkreader/darkreader/issues/3918. I'm afraid that the MDN team also will just toss this issue back to them. Please do some co-work to solve this issue 🙏 (cc @gusted)

**Comment by Gusted** [comment]
> @Gusted What could be a reason when Dark Reader opens an empty shadow root and insert styles there?

It's basic practice for Dark Reader to insert those 2 styles. The first one is to make overriding inline styles work. The second one is the override that's provided by [dynamic-theme-fixes.config](https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config) for the correct site.

https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/index.ts#L130 This functions add those styles into it.

**Comment by Gusted** [comment]
Opened up a PR to fix this problem #539.
As it simply wants to remove an `undefined` or `null` in some cases a simple check should prevent this.
![image](https://user-images.githubusercontent.com/25481501/98576559-fe430a80-22ba-11eb-9a88-00e56cba41cb.png)
Same error when you try to remove an non-object.

**Comment by saschanaz** [comment]
> It's basic practice for Dark Reader to insert those 2 styles. The first one is to make overriding inline styles work. The second one is the override that's provided by [dynamic-theme-fixes.config](https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config) for the correct site.

Could it be done in a lazy way? It doesn't seem right to insert styles when the root is empty.

**Comment by Gusted** [comment]
> Could it be done in a lazy way? 

It's static so it doesn't have any checks in place, only the dynamic styles are being placed when needed.

>  It doesn't seem right to insert styles when the root is empty.

It insert the styles after Dark Reader detects that an new root is opened as this should be filled with elements later and waiting on the shadowroot to wait for elements coming in doesn't seems to be a good practice in my eyes.

**Comment by saschanaz** [comment]
>only the dynamic styles are being placed when needed.

That's good, but why can't the static ones be lazily inserted only when that happens?

**Comment by Gusted** [comment]
> That's good, but why can't the static ones be lazily inserted only when that happens?

Not really.... Because this style `override` is for fixes. Because the shadow root doesn't necessary have dynamic style it can have a style that's being fixed by the `override` but doesn't have dynamic styles and therefore won't get actually fixed.
