### ISSUE TITLE
Revisit old issue with possible solution around tabbing and CSS examples

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#548]
See https://github.com/mdn/interactive-examples/issues/349 and https://github.com/mdn/interactive-examples/pull/523/files

**Comment by caugner** [comment]
@schalkneethling Do you remember what this issue was about?

I looked at the referenced issue and PR, but it isn't very clear to me. Also, https://github.com/mdn/bob/pull/758 just resolved an outstanding issue with regard to the wrong tab being open by default. Could this be related?

**Comment by schalkneethling** [comment]
This was actually fixed by @hidde recently. So, we can close.
