### ISSUE TITLE
Error when running example code for Javascript doc - String.match()

### ISSUE THREAD

**Issue by MEF4232** [mdn/bob#574]
Was reading about [String.match()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) and testing the example code snippets. The code snippet for [Using named capturing groups](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#using_named_capturing_groups) does not work (see screenshot below)

<img width="1022" alt="Screen Shot 2021-05-10 at 1 05 56 PM" src="https://user-images.githubusercontent.com/22859165/117697435-774eec00-b190-11eb-98e9-a1cbbeaae030.png">

**Comment by schalkneethling** [comment]
@wbamberg Ok, so adding this solves the problem:

```javascript
if (!objectName.constructor || !objectName.prototype) {
    var formattedChild = '';
    var start = true;
    for (var key in input) {
        if (start) {
            start = false;
        } else {
            formattedChild = formattedChild + ', ';
        }
        formattedChild =
            formattedChild + key + ': ' + this.formatOutput(input[key]);
    }
    return 'Object { ' + formattedChild + ' }';
}
```

What I am really curious about is what type of `Object` this is that has neither a `constructor` nor a `prototype`. According to the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor):

`All objects (with the exception of objects created with Object.create(null)) will have a constructor property`

 Are there other instances of this other than on `String.match`?

**Comment by karlcow** [comment]
Just to remember for later for myself (but if it's interesting to others)

* [Prototype methods, objects without __proto__](https://javascript.info/prototype-methods)
* [createMatchResultTemplateObject with Indices has groups only property](https://searchfox.org/mozilla-central/rev/b52cf6bbe214bd9d93ed9333d0403f7d556ad7c8/js/src/vm/RegExpObject.cpp#902-913) and [createMatchResultTemplateObject](https://searchfox.org/mozilla-central/rev/b52cf6bbe214bd9d93ed9333d0403f7d556ad7c8/js/src/vm/RegExpObject.cpp#890)

**Comment by moztcampbell** [comment]
Searching the ECMAScript spec for uses of `OrdinaryObjectCreate(null)` I find a few:
- @@unscopables properties such as `[1,2,3][Symbol.unscopables]`
- `import.meta` in modules
- The regexp named capture groups described in their issue

So it is very uncommon.

**Comment by schalkneethling** [comment]
Thank you for the extremely valuable info @karlcow and @moztcampbell ❤️
