### ISSUE TITLE
Forced focus to example textbox on every (?) page can't be escaped?

### ISSUE THREAD

**Issue by tshinnic** [mdn/bob#593]
First noticed as inability to move backwards/forwards in page history. Then realized that tab/shift-tab would not let me escape the initial example textbox. Only mouse interaction to focus outside the textbox would allow tabbing to other controls or using alt-leftarrow or alt-rightarrow to action page history.

Example page would be [String.prototype.codePointAt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt)

* Why is there a forced focus on page load or refresh on any initial example textbox?

* Why is there no mechanism to escape once focused in the textbox?

This is beyond inconvenient but also quite against accessibility?

(this on Chrome 91, Edge 92, FF 90 and Win10)

**Comment by peterbe** [comment]
@schalkneethling I transferred this issue to here. Seems like a pretty significant bug.

**Comment by tshinnic** [comment]
What does use of [this option](https://github.com/mdn/bob/blob/afa4e2fcb37725072d9f7b8a9a816c5c8af25f17/editor/js/editable-js.js#L32-L36) do?

> [autofocus: boolean](https://codemirror.net/doc/manual.html#option_autofocus)
> Can be used to make CodeMirror focus itself on initialization. Defaults to off.

Apparently original code from 3+ years ago, perhaps something recently changing elsewhere has caused this effort to surface so obtrusively? Perhaps experimenting with that option commented out so that it can default to 'false' would be worth a try?

**Comment by peterbe** [comment]
@schalkneethling Can you please test to turn that to `false` and see how it behaves?

**Comment by peterbe** [comment]
This bug is so annoying that when you go to https://developer.mozilla.org/en-US/docs/MDN/Kitchensink it always automatically scrolls you down to this interactive example:
<img width="509" alt="Screen Shot 2021-08-04 at 12 58 21 PM" src="https://user-images.githubusercontent.com/26739/128222896-0b98cbb2-34a0-4d21-8cf2-d0a6f3e0e009.png">
