### ISSUE TITLE
Adding wasm interactive examples

### ISSUE THREAD

**Issue by MendyBerger** [mdn/bob#606]
I recently added docs for wasm control flow operators, and I hope to continue adding additional reference docs for other parts of wasm like memory and numerical operations.

I added examples to all pages, but those examples are not interactive. So here's my question, would you folks be open to me adding a new interactive example type for wasm? I think it would be most useful as tabbed where one tab is for the wasm and another one is for js, since wasm is basically useless without js.

I've already done the basic work for this, but before I'm putting in more work I'd like to make sure you folks are on board.

CC @schalkneethling, I was told that you're the one that I should talk to about this.

**Comment by schalkneethling** [comment]
Hey @MendyBerger! This sounds pretty dang neat! Can you reuse the existing code and build process or do you need to add pieces to make this work? Either way, would be happy to review. @Rumyra and @ddbeck what do you reckon?

**Comment by MendyBerger** [comment]
I'll probably be able to build most of it by reusing other parts, but I'll need to add a wasm compiler on top of all that.

I was thinking of using the `wabt` npm package as the compiler.

**Comment by schalkneethling** [comment]
> I'll probably be able to build most of it by reusing other parts, but I'll need to add a wasm compiler on top of all that.
> 
> I was thinking of using the `wabt` npm package as the compiler.

So, I guess we will run this as part of the build? I ask, because while I seems possible to use this in the browser(https://www.npmjs.com/package/wabt), I am not sure of the potential performance impact/security.

**Comment by MendyBerger** [comment]
If we want those examples to be interactive than it has to run in the browser so that it can compile the `wat` code to `wasm`.

Performance: I don't think there's a need to worry, the example modules will probably be quite small, so compiling should probably not take more then a few hundred milliseconds even on very under-powered machines.

Just to be sure I created a small example that compiles a wasm module in the browser, I tried it on a very low-end Android tablet and it compiled in less than 400ms (https://jsbin.com/bagakibita/edit?html,js,output).


Security: I'm not sure what the process is to approve a third party dependency, but I think that the people behind this package are very trustworthy. The wabt js wrapper is maintained by the AssemblyScript team (very prominent in the wasm space), and wabt itself is maintained by no other then the WebAssembly working group themselves (https://github.com/WebAssembly/wabt).

**Comment by Rumyra** [comment]
Yes this sounds good to me - some thoughts:

* I'm pro keeping examples within the MDN eco system rather than third parties and this does that
* It would be good if the interface and the functionality on 'how to add' was similar to our current interactive examples
