### ISSUE TITLE
Issue with "RegExp() constructor": (short summary here please)

### ISSUE THREAD

**Issue by vivita0** [mdn/bob#625]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp

#### What information was incorrect, unhelpful, or incomplete?
Appears to be incorrect

#### Specific section or headline?
In the top of the document where there's a little test coding area labeled "JavaScript Demo: RegExp Constructor", when I run the code as written, it does not give the expected results as shown in the comments. Instead, I get the following results: 
> Object {  }
> Object {  }
> false

#### What did you expect to see?
In the comments provided, I should see:
// expected output: /\w+/
// expected output: /\w+/
// expected output: false

#### Did you test this? If so, how?
I just clicked on 'run' without changing the code that came up when I loaded the page

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/regexp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/regexp/index.md
* Last commit: https://github.com/mdn/content/commit/5e90bae6518d8d2329ad5c97009208f36b06a9c5
* Document last modified: 2021-10-15T16:06:26.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
It's fixed :)
