### ISSUE TITLE
Issue with "void operator": example output does not match expected output

### ISSUE THREAD

**Issue by alexschrod** [mdn/bob#710]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

#### What information was incorrect, unhelpful, or incomplete?
The first example on the page says
> ```js 
>  console.log(e);
>  // expected output: ReferenceError: test is not defined
> ```

but when I run it, it prints
```
> "boo!"
> Object {  }
```

#### Specific section or headline?
JavaScript Demo: Expressions - void operator

#### What did you expect to see?
That the actual output matches the expected output

#### Did you test this? If so, how?
If you replace `console.log(e)` with `console.log(e.toString())`, the actual output matches the expected output.

I was going to fork and fix it in a PR, but the code example is brought in using a command like `EmbedInteractiveExample("pages/js/expressions-voidoperator.html")` and I can't figure out where this file lives, so you'll have to do it yourselves.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/void`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/void/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
Same issue occurs in [preventExtensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions), [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) and WeakSet [add](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet/add)

**Comment by wbamberg** [comment]
Possible fix-> https://github.com/mdn/bob/pull/745.

**Comment by NiedziolkaMichal** [comment]
It's fixed :)
