### ISSUE TITLE
Interactive examples flash to light mode for a brief instant on some occasions when pressing the Reset button in dark mode

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#732]
@schalkneethling it no longer reverts to light mode in any of my testing. The applet does, however, flash to light mode for a brief instant on some occasions when pressing the Reset button in dark mode. Not sure if that issue would even be addressable or not

_Originally posted by @SandyClams in https://github.com/mdn/yari/issues/5405#issuecomment-1064537138_

**Comment by caugner** [comment]
Reproduced as follows:

1. Open https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now#try_it
2. Switch to Light theme.
3. Press "Reset" button in interactive example.

https://user-images.githubusercontent.com/495429/166441736-93e21bc5-59a2-4b25-8a4c-a71aed156003.mov

**Comment by caugner** [comment]
I can no longer reproduce this issue, so it looks like it is resolved.
