### ISSUE TITLE
"Inter" web font loads are 404

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#749]
Got this report from Chris Peterson on Matrix:

When testing some code in the DevTools console while reading an MDN page, I noticed that some "Inter" web font loads are 404.

1. Open the DevTools console.
2. Load an MDN page with example code, such as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
3. In the console, I see the following error: `downloadable font: download failed (font-family: "Inter" style:normal weight:1..999 stretch:75..100 src index:1): status=2147746065 source: https://interactive-examples.mdn.mozilla.net/media/fonts/Inter.var.woff2`

**Comment by cpeterso** [comment]
If I try to load https://interactive-examples.mdn.mozilla.net/media/fonts/Inter.var.woff2 directly, I get the following error page:

```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: media/fonts/Inter.var.woff2
    RequestId: 8GW70MYC9JM7H10N
    HostId: FL5vjHHVbuoPngYXFp/JnWPZhwwiSon2wQpzD68vPHuKuSz8UZJfG8foHainUjYVxRvgEAACTBI=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html
```

**Comment by OnkarRuikar** [comment]
I get more exceptions on the same page in Chrome on Windows 10:
> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://interactive-examples.mdn.mozilla.net') does not match the recipient window's origin ('https://developer.mozilla.org').                                  utils.ts:51

And in incognito mode:
> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at HTMLDocument.<anonymous> (https://interactive-examples.mdn.mozilla.net/js/editor-js.js?v=89b8260:1:6310)

**Comment by caugner** [comment]
FWIW The font is available on https://developer.mozilla.org/, but webpack adds a hash to the filename:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/495429/163649140-9815b2a0-9780-4208-b97f-827c6977e7ad.png">

**edit**: And it's defined in the `editor-js.css`:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/495429/163649320-8165c591-5975-43a9-80ce-29d322c96908.png">

https://github.com/mdn/bob/blob/28c31ec392efe83a030115515154c51095bac56f/editor/css/editor-libs/ui-fonts.css#L3-L5
