### ISSUE TITLE
bug: using `new Function` in interactive examples seems to not work as expected

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#808]
While reading over a request for assessment on Discourse we discovered that the interactive example editor fails to execute the following code block correctly:

```js
let x = 60; 
var mike = new Function('return x;'); 
console.log(mike())
```

If you execute the above in say, Codepen, it will log `60` to the console. With the interactive example editor, however, it logs out `"Error: x is not defined"`. What will happen in the editor is the following:

```js
new Function("let x = 60;var mike = new Function('return x;');console.log(mike())")();
```

Not sure if it has something to do with what CodeMirror returns here:
https://github.com/mdn/bob/blob/main/editor/js/editable-js.js#L24

**Comment by NiedziolkaMichal** [comment]
Provided example is executed in updateOutput function present in editable-js.js, by doing following operation:
```
new Function(exampleCode)();
```
Now if you would create new js file with following content:
```
var exampleCode = "var x = 60;var mike = new Function('return x;');console.log(mike());";
new Function(exampleCode)();
```
result is the same. The reason is, content of `Function` constructor is always executed on global scope, while var "x" lives inside nested function, therefore it's not accessible. Interestingly if you omit "var" keyword in the example, global variable will be created and output will be 60.

Solution to this would be to use `eval(exampleCode)`, but is it worth it?

**Comment by schalkneethling** [comment]
> Solution to this would be to use `eval(exampleCode)`, but is it worth it?

Thank you for your comment. That is a good question. For the most part these work well. It was just unfortunate to see the editor causing confusion for the learner as opposed to being an aid to help them understand the topic better. Something to keep track of I believe.

**Comment by yarusome** [comment]
How about running the code in a worker like this:

```js
function updateOutput(exampleCode) {
  const workerCode = `"use strict"; for (const [key, value] of Object.entries(console)) { console[key] = new Proxy(value, { apply(target, thisArg, args) { postMessage([key, args]); } }); } ${exampleCode}`;
  const workerURL = URL.createObjectURL(
    new Blob([workerCode], { type: "text/javascript" })
  );
  const worker = new Worker(workerURL);
  URL.revokeObjectURL(workerURL);

  worker.addEventListener(
    "message",
    () => output.classList.add("fade-in"),
    { once: true, passive: true }
  );
  output.addEventListener(
    "animationend", 
    () => output.classList.remove("fade-in"),
    { once: true, passive: true }
  );

  worker.onmessage = (e) => {
    const [key, ...params] = e.data;
    console[key](...params);
  };
  worker.onerror = (e) => {
    e.preventDefault();
    output.textContent = e.message;
  };

  worker.postMessage(null);
}
```

This also handles codes as innocuous as:

```js
let length = 1;
new Function(`console.log(length)`)();
```

The cons of this approach are:

- a few web APIs are unavailable in workers;
- ~The `worker-src` CSP needs adjusting.~ The above code, with `output.textContent = e.message` replaced by `console.log(e.message)` and all the other `output`s removed, runs successfully in the current interactive examples' console.

---

It can be even better by using closures to abort previously initiated script running:

```js
self.updateOutput = (() => {
  let worker = { terminate() {} };

  return (exampleCode) => {
    worker.terminate();

    const workerCode = `"use strict"; for (const [key, value] of Object.entries(console)) { console[key] = new Proxy(value, { apply(target, thisArg, args) { postMessage([key, args]); } }); } ${exampleCode}`;
    const workerURL = URL.createObjectURL(
      new Blob([workerCode], { type: "text/javascript" })
    );
    worker = new Worker(workerURL);
    URL.revokeObjectURL(workerURL);

    worker.addEventListener(
      "message",
      () => output.classList.add("fade-in"),
      { once: true, passive: true }
    );
    output.addEventListener(
      "animationend", 
      () => output.classList.remove("fade-in"),
      { once: true, passive: true }
    );

    worker.onmessage = (e) => {
      const [key, ...params] = e.data;
      console[key](...params);
    };
    worker.onerror = (e) => {
      e.preventDefault();
      output.textContent = e.message;
    };

    worker.postMessage(null);
  };
})();
```

**Comment by caugner** [comment]
This seems to be a limitation of our code editor implementation, but I don't really think it's a problem:

1. There is only [one occurrence](https://github.com/mdn/interactive-examples/blob/b6d6893514bcada69f55ac0aaba8d2e6140107da/live-examples/js-examples/function/function-constructor.js#L1) of `new Function(` in the interactive-examples code base.
2. MDN now has it's own playground, and [the code works in it](https://developer.mozilla.org/en-US/play?id=gHjHcXTUyQm6S%2F2qnFg%2Fk2qIyiKlcXJBYDQDutcNmiHZoELs5qJXAon8s2Cw5Ft1wjETRxXibBsyig8T).

Therefore I will go ahead and close this issue as "won't fix". Don't hesitate to comment with more information, if you think this should be fixed.
