### ISSUE TITLE
Color of css ID selector

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/bob#811]
ID selectors in tabbed examples are unreadable in dark mode because of poor color choice. Right now color #30a is used, which makes selector look like that:

![image](https://user-images.githubusercontent.com/100634371/173192390-c6e5dd37-7ae2-4d7d-af66-4f53a58bcf6b.png)

I don't think there is any example using id selector right now, but I am about to add one in ::part pseudo-element.

**Comment by Rumyra** [comment]
Duplicate of https://github.com/mdn/bob/issues/774
