### ISSUE TITLE
Migrate to CodeMirror v6

### ISSUE THREAD

**Issue by caugner** [mdn/bob#851]
## Background

So far, we have been bundling CodeMirror v5 ourselves by concatenating and minifiying several CodeMirror source files:

https://github.com/mdn/bob/blob/1669f37ca65db82afad00fcd8112c454d96d3068/lib/bundler.js#L70-L86

We have been building to bundles:

1. `codeMirror` (a.k.a. `codemirror-5-50-2`):
  https://github.com/mdn/bob/blob/1669f37ca65db82afad00fcd8112c454d96d3068/bundles.json#L4-L13
2. `codeMirrorTabbed` (a.k.a. `codemirror-tabbed-5-50-2`)
  https://github.com/mdn/bob/blob/1669f37ca65db82afad00fcd8112c454d96d3068/bundles.json#L17-L28

## Problem

In CodeMirror v6, this is no longer possible as `node_modules/codemirror` and `node_modules/@codemirror/*` no longer contain sources, but only a `dist/` folder with a single ESM (`index.js`) and CommonJS (`index.cjs`) entrypoint.

**Comment by queengooborg** [comment]
From what it looks like, CodeMirror v6 contains a complete architectural rewrite that heavily depends on bundlers, as each individual component has been separated into its own package (ex. JS language support, et. al.).  The main `codemirror` package has now been replaced with a completely barebones setup.

I _think_ Browserify is powerful enough to handle this, but we may want to research other options like Rollup or Vite as our dependency count scales up.

**Comment by caugner** [comment]
@queengooborg Thank you! Are you aware of any pros/cons of staying with browserify vs moving to Rollup or Vite?

**Comment by queengooborg** [comment]
Some pros I know of for Rollup and Webpack are much faster build times and ESM module support.  Vite, I'm not quite as familiar with as I've only heard the name, but I've heard good things about it!

**Comment by caugner** [comment]
If you tackle this, you can go with whatever of these three tools you prefer. I have also heard good things about Vite (almost instant builds?), we're currently using Webpack in yari, and Florian had a good impression of Rollup when experimenting with it in yari (not committed). 👍
